spring.jpa.hibernate.ddl-auto=none
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/raynet_crm}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:raynet_app_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:raynet_app_password}

rcrm.api.url=${RCRM_API_URL:https://app.raynet.cz/api/v2/}
rcrm.api.key=${RCRM_API_KEY:}
rcrm.api.username=${RCRM_API_USERNAME:example-user@example.com}
rcrm.api.instancename=${RCRM_API_INSTANCENAME:example-instance}
rcrm.api.email.from=${RCRM_API_EMAIL_FROM:example-user@example.com}
rcrm.api.email.to=${RCRM_API_EMAIL_TO:}

spring.mail.host=smtp.sendgrid.net
spring.mail.port=587
spring.mail.username=${SPRING_MAIL_USERNAME:apikey}
spring.mail.password=${SPRING_MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

flyway.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/raynet_crm}
flyway.user=${SPRING_DATASOURCE_USERNAME:raynet_app_user}
flyway.password=${SPRING_DATASOURCE_PASSWORD:raynet_app_password}
flyway.schemas=public
flyway.locations=classpath:db/migration